"""add cash session

Revision ID: 0503ac70c8ed
Revises: f0da159c70ab
Create Date: 2026-03-02 17:25:35.023991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0503ac70c8ed'
down_revision = 'f0da159c70ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('starting_cash', sa.Float(), nullable=False),
    sa.Column('counted_cash', sa.Float(), nullable=False),
    sa.Column('counted_card', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_session')
    # ### end Alembic commands ###
