"""add logo_url

Revision ID: 0521a5f0bda1
Revises: d3fc37d33b55
Create Date: 2026-04-23 19:53:14.969363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0521a5f0bda1'
down_revision = 'd3fc37d33b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
