"""add_billing_fields_to_business

Revision ID: 2122204fac0a
Revises: 5462ca9240c4
Create Date: 2026-04-20 12:20:58.509104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2122204fac0a'
down_revision = '5462ca9240c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_api_key', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('billing_branch_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('billing_pos_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('billing_pos_name')
        batch_op.drop_column('billing_branch_name')
        batch_op.drop_column('billing_api_key')

    # ### end Alembic commands ###
