"""Add cost_price to Product

Revision ID: 4e2449010918
Revises: 8b9c0b57b229
Create Date: 2026-03-25 12:30:19.099897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2449010918'
down_revision = '8b9c0b57b229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('cost_price')

    # ### end Alembic commands ###
