"""empty message

Revision ID: 5462ca9240c4
Revises: d9674ba7d481
Create Date: 2026-04-20 09:40:08.023244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5462ca9240c4'
down_revision = 'd9674ba7d481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sii_document_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sii_folio', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sii_pdf_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sii_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('sii_status')
        batch_op.drop_column('sii_pdf_url')
        batch_op.drop_column('sii_folio')
        batch_op.drop_column('sii_document_type')

    # ### end Alembic commands ###
