"""empty message

Revision ID: 8b9c0b57b229
Revises: d159e31b5920
Create Date: 2026-03-09 17:10:40.264974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9c0b57b229'
down_revision = 'd159e31b5920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rut', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('giro_comercial', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('giro_comercial')
        batch_op.drop_column('rut')

    # ### end Alembic commands ###
