"""empty message

Revision ID: d159e31b5920
Revises: 742561f77e1f
Create Date: 2026-03-09 15:52:49.817363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd159e31b5920'
down_revision = '742561f77e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.String(length=50), server_default='basico', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('subscription_plan')

    # ### end Alembic commands ###
