"""add_sii_xml_fields

Revision ID: d3fc37d33b55
Revises: 2122204fac0a
Create Date: 2026-04-22 16:04:02.345830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fc37d33b55'
down_revision = '2122204fac0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sii_signed_xml', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sii_ted_xml', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('sii_ted_xml')
        batch_op.drop_column('sii_signed_xml')

    # ### end Alembic commands ###
