"""add min_stock to product

Revision ID: d42a5590cffb
Revises: f9af01631342
Create Date: 2026-03-02 15:15:28.355813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42a5590cffb'
down_revision = 'f9af01631342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_stock', sa.Integer(), nullable=False, server_default='5'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('min_stock')

    # ### end Alembic commands ###
